// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF0nxj7DWM-7s8IY5zVWCNC3OO7GglD6U',
    appId: '1:921805432727:web:84a4da92951a02f7a286d2',
    messagingSenderId: '921805432727',
    projectId: 'shipment-app-7f6c3',
    authDomain: 'shipment-app-7f6c3.firebaseapp.com',
    storageBucket: 'shipment-app-7f6c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA57FPnbokaN-VE2c8EIdPNcdVi8BGhdA8',
    appId: '1:921805432727:android:f8eb262460aacd34a286d2',
    messagingSenderId: '921805432727',
    projectId: 'shipment-app-7f6c3',
    storageBucket: 'shipment-app-7f6c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTN_Z0ndb28WNbRBVuxIN4e44y5DvFtRM',
    appId: '1:921805432727:ios:7ca67669c5245f94a286d2',
    messagingSenderId: '921805432727',
    projectId: 'shipment-app-7f6c3',
    storageBucket: 'shipment-app-7f6c3.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTN_Z0ndb28WNbRBVuxIN4e44y5DvFtRM',
    appId: '1:921805432727:ios:7ca67669c5245f94a286d2',
    messagingSenderId: '921805432727',
    projectId: 'shipment-app-7f6c3',
    storageBucket: 'shipment-app-7f6c3.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF0nxj7DWM-7s8IY5zVWCNC3OO7GglD6U',
    appId: '1:921805432727:web:e97848e1e6f5060da286d2',
    messagingSenderId: '921805432727',
    projectId: 'shipment-app-7f6c3',
    authDomain: 'shipment-app-7f6c3.firebaseapp.com',
    storageBucket: 'shipment-app-7f6c3.firebasestorage.app',
  );

}